name: Kelp forest benthic community structure at the California Channel Islands -- Ecological Archives 2013

description: David J. Kushner, Andrew Rassweiler, John P. McLaughlin, Kevin D. Lafferty. 2013. A multi-decade time series of kelp forest community structure at the California Channel Islands. Ecology 94:2655.

shortname: COM02R

tags: taxon > Benthic, Spatial Scale > Local, Data Type > Time Series, Data Type > Observational

table: COM02R_BENTHIC_DENS http://esa.pubs.org/archive/ecol/E094/245/Benthic%Density%20Data.csv