name: Kelp forest benthic community structure at the California Channel Islands -- Ecological Archives 2013

description: David J. Kushner, Andrew Rassweiler, John P. McLaughlin, Kevin D. Lafferty. 2013. A multi-decade time series of kelp forest community structure at the California Channel Islands. Ecology 94:2655.

shortname: COM02Q

tags: taxon > Fish, Spatial Scale > Local, Data Type > Time Series, Data Type > Observational

table: COM02Q_FISH_DENS, http://esapubs.org/archive/ecol/E094/245/Fish%Density%20data.csv
*nulls: 'NA'

table: COM02Q_RDFC, http://esapubs.org/archive/ecol/E094/245/RDFC%20data.csv
*nulls: 'NA'

table: COM02Q_FISH_DENS_HEADER_DESCRIPT, http://esapubs.org/archive/ecol/E094/245/Table9A_fish_density_headers.csv

table: COM02Q_FISH_DENS_VAR_DESCRIPT, http://esapubs.org/archive/ecol/E094/245/Table9B_fish_density_variables.csv

table: COM02Q_RDFC_HEADER_DESCRIPT, http://esapubs.org/archive/ecol/E094/245/Table10A_RDFC_headers.csv

table: COM02Q_RDFC_VAR_DESCRIPT, http://esapubs.org/archive/ecol/E094/245/Table10B_RDFC_variables.csv