name: A multi-decade time series of kelp forest community structure at San Nicolas Island, California (USA). Ecology 94:2654.

description: Michael C. Kenner, James A. Estes, M. Tim Tinker, James L. Bodkin, Robert K. Cowen, Christopher Harrold, Brian B. Hatfield, Mark Novak, Andrew Rassweiler, and Daniel C. Reed. 2013. A multi-decade time series of kelp forest community structure at San Nicolas Island, California (USA). Ecology 94:2654.

shortname: Kenner2013

tags: Biome > Marine, Spatial Scale > Local, Data Type > Time Series, Data Type > Compilation

# Tables below provide description of variables:

table: BENTHIC_DENSITY, http://esapubs.org/archive/ecol/E094/244/Benthic%20density%20raw%20data.csv
table: BENTHIC_DENSITY_SUMMARY, http://esapubs.org/archive/ecol/E094/244/Benthic%20density%20summary%20data.csv
table: BENTHIC_COVER, http://esapubs.org/archive/ecol/E094/244/Benthic%20cover%20raw%20data.csv
table: BENTHIC_COVER_SUMMARY, http://esapubs.org/archive/ecol/E094/244/benthic%20cover%20summary%20data.csv
table: MIDWATER_FISH_DENSITY, http://esapubs.org/archive/ecol/E094/244/Midwater%20fish%20density%20raw%20data.csv
table: MIDWATER_FISH_DENSITY_SUMMARY, http://esapubs.org/archive/ecol/E094/244/Midwater%20fish%20density%20summary%20data.csv
table: BENTHIC_FISH_DENSITY, http://esapubs.org/archive/ecol/E094/244/Benthic%20fish%20density%20raw%20data.csv
table: BENTHIC_FISH_DENSITY_SUMMARY, http://esapubs.org/archive/ecol/E094/244/Benthic%20fish%20density%20summary%20data.csv
table: GIANT_KELP_SIZE, http://esapubs.org/archive/ecol/E094/244/Giant%20kelp%20size%20frequency.csv

# Supplemental information including variable and header description tables:

table: MONITORING_SITES_AND_COORDINATES, http://esapubs.org/archive/ecol/E094/244/Table1_Monitoring_Stations.csv
table: SEA_OTTER_ABUNDANCE, http://esapubs.org/archive/ecol/E094/244/Table2_independent_sea_otters.csv
table: SEA_OTTER_PUP_ABUNDANCE, http://esapubs.org/archive/ecol/E094/244/Table3_sea_otter_pups.csv
table: SPECIES_SAMPLED, http://esapubs.org/archive/ecol/E094/244/Table4_Species_sampled.csv
table: BENTHIC_DENSITY_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table5A_benthic_density_raw_headers.csv
table: BENTHIC_DENSITY_VARS, http://esapubs.org/archive/ecol/E094/244/Table5B_benthic_density_raw_variables.csv
table: BENTHIC_DENSITY_SUMMARY_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table6A_benthic_density_summary_headers.csv
table: BENTHIC_DENSITY_SUMMARY_VARS, http://esapubs.org/archive/ecol/E094/244/Table6B_benthic_density_summary_variables.csv
table: BENTHIC_COVER_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table7A_benthic_cover_raw_headers.html
table: BENTHIC_COVER_VARS, http://esapubs.org/archive/ecol/E094/244/Table7B_benthic_cover_raw_variables.html
table: BENTHIC_COVER_SUMMARY_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table8A_benthic_cover_summary_headers.html
table: BENTHIC_COVER_SUMMARY_VARS, http://esapubs.org/archive/ecol/E094/244/Table8B_benthic_cover_summary_variables.html
table: MIDWATER_FISH_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table9A_midwater_fish_raw_headers.html
table: MIDWATER_FISH_VARS, http://esapubs.org/archive/ecol/E094/244/Table9B_midwater_fish_raw_variables.html 
table: MIDWATER_FISH_SUMMARY_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table10A_midwater_fish_summary_headers.html
table: MIDWATER_FISH_SUMMARY_VARS, http://esapubs.org/archive/ecol/E094/244/Table10B_midwater_fish_summary_variables.html
table: BENTHIC_FISH_DENSITY_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table11A_benthic_fish_raw_headers.html
table: BENTHIC_FISH_DENSITY_VARS, http://esapubs.org/archive/ecol/E094/244/Table11B_benthic_fish_raw_variables.html
table: BENTHIC_FISH_DENSITY_SUMMARY_HEADERS,http://esapubs.org/archive/ecol/E094/244/Table12A_benthic_fish_summary_headers.html
table: BENTHIC_FISH_DENSITY_SUMMARY_VARS,http://esapubs.org/archive/ecol/E094/244/Table12B_benthic_fish_summary_variables.html
table: GIANT_KELP_SIZE_HEADERS, http://esapubs.org/archive/ecol/E094/244/Table14A_giant_kelp_size_frequency_headers.html
table: GIANT_KELP_SIZE_VARS, http://esapubs.org/archive/ecol/E094/244/Table14B_giant_kelp_size_frequency_variables.html