name: Kelp forest benthic community structure at the California Channel Islands -- Ecological Archives 2013

description: David J. Kushner, Andrew Rassweiler, John P. McLaughlin, Kevin D. Lafferty. 2013. A multi-decade time series of kelp forest community structure at the California Channel Islands. Ecology 94:2655.

shortname: Kushner2013

tags: Biome > Marine, Spatial Scale > Local, Data Type > Time Series, Data Type > Observational

# Data tables:

table: BENTHIC_DENS, http://esapubs.org/archive/ecol/E094/245/Benthic%20Density%20Data.csv
table: BENTHIC_COVER, http://esapubs.org/archive/ecol/E094/245/Benthic%20Cover%20Data.csv
table: FISH_DENS, http://esapubs.org/archive/ecol/E094/245/Fish%Density%20data.csv
table: RDFC, http://esapubs.org/archive/ecol/E094/245/RDFC%20data.csv
table: FISH_SIZE-FREQ, http://esapubs.org/archive/ecol/E094/245/Fish%20size%20frequency%20data.csv
table: INVERT_SIZE-FREQ, http://esapubs.org/archive/ecol/E094/245/Invertebrate%20Size%20Frequency.csv
table: GIANT_KELP-SIZE-FREQ, http://esapubs.org/archive/ecol/E094/245/Giant%20kelp%20size%20frequency.csv
table: GIANT_KELP_DENSITY, http://esapubs.org/archive/ecol/E094/245/Giant%20kelp%20supplementary%20density%20data.csv
table: ARTIFICICAL_RECRUIT_MODULE, http://esapubs.org/archive/ecol/E094/245/Artifical%20recruitment%20module%20data.csv
table: SUBTIDAL_TEMP, http://esapubs.org/archive/ecol/E094/245/Subtidal%20temperature%20data.csv

# Supplemental information including variable and header description tables:

table: MONITORING_SITES_AND_COORDINATES, http://esapubs.org/archive/ecol/E094/245/Table1_Monitoring_sites.csv
table: HISTORY_OF_FISHING_RESTRICTIONS, http://esapubs.org/archive/ecol/E094/245/Table2_History_of_fishing_restrictions.csv
table: SPECIES_MONITORED_BY_METHOD, http://esapubs.org/archive/ecol/E094/245/Table3_Species_monitored.csv
table: BENTHIC_DENS_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table4A_benthic_density_headers.html
table: BENTHIC_DENS_VARS, http://esapubs.org/archive/ecol/E094/245/Table4B_benthic_density_variables.html
table: BENTHIC_COVER_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table7A_benthic_cover_headers.html
table: BENTHIC_COVER_VARS, http://esapubs.org/archive/ecol/E094/245/Table7B_benthic_cover_variables.html
table: FISH_DENS_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table9A_fish_density_headers.csv
table: FISH_DENS_VARS, http://esapubs.org/archive/ecol/E094/245/Table9B_fish_density_variables.csv
table: RDFC_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table10A_RDFC_headers.csv
table: RDFC_VARS, http://esapubs.org/archive/ecol/E094/245/Table10B_RDFC_variables.csv
table: FISH_SIZE_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table12A_fish_size_frequency_headers.html
table: FISH_SIZE_VARS, http://esapubs.org/archive/ecol/E094/245/Table12B_fish_size_frequency_variables.html
table: INVERT_SIZE_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table13A_invertebrate_size_frequency_headers.html
table: INVERT_SIZE_VARS, http://esapubs.org/archive/ecol/E094/245/Table13B_invertebrate_size_frequency_variables.html
table: GKELP_SIZE_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table14A_giant_kelp_size_frequency_headers.html
table: GKELP_SIZE_VARS, http://esapubs.org/archive/ecol/E094/245/Table14B_giant_kelp_size_frequency_variables.html
table: GKELP_DENS_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table15A_giant_kelp_supplementary_density_headers.html
table: GKEP_DENS_VARS, http://esapubs.org/archive/ecol/E094/245/Table15B_giant_kelp_supplementary_density_variables.html
table: ART_RECRUIT_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table16A_artificial_recruitment_module_headers.html
table: ART_RECRUIT_VARS, http://esapubs.org/archive/ecol/E094/245/Table16B_artificial_recruitment_module_variables.html
table: SUBTIDAL_TEMP_HEADERS, http://esapubs.org/archive/ecol/E094/245/Table17A_subtidal_temperature_headers.html
table: SUBTIDAL_TEMP_VARS, http://esapubs.org/archive/ecol/E094/245/Table17B_subtidal_temperature_variables.html